### ISSUE TITLE
Test with latest binary?

### ISSUE THREAD

**Issue by rodneyrod** [hdhoang/harbour-syncthing#1]
Have you checked the project against the latest binary?
I can test it myself, is it as easy as swapping out the syncthing binary with the latest version?

**Comment by hdhoang** [comment]
ah, this is abandonware now, sorry.

regarding your concern, it's been 2yrs since v0.10 so I don't think it will work smoothly.

**Comment by rodneyrod** [comment]
Ahh shame, so there's no chance of getting this working on Sailfish OS again, even with the included web interface? Because really that's all that's needed.

**Comment by hdhoang** [comment]
Hm, my package installs the service file, then asks systemd to start it. I think it would just work with a newer syncthing binary. Someone might even patch the spec file to extract it from upstream's package.

Another thing, my sailfish compatible phone is in the shop, I can't test this anymore.
